name: Discord2FA
version: 3.5
author: EylexLive
main: io.github.eylexlive.discord2fa.Discord2FA
description: 2FA plugin with Discord.
softdepend:
  - AuthMe
  - LoginSecurity

commands:
  auth:
    aliases:
      - dcauth
  discord2fa:
    aliases:
      - dc2fa
      - dca